- hosts: frontend
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Update all
    yum:
      name: '*'
      state: latest
  - name: Install Apache
    yum:
      name: httpd
      state: installed
  - name: Create HTML File
    shell: echo "<p><h1>Hello World from $(hostname -f)</h1></p><p><h2>Updated using Ansible</h2></p>" > /var/www/html/index.html
    args:
      executable: /bin/bash
    notify:
      - Reload Apache
  handlers:
  - name: Reload Apache
    service:
      name: httpd
      state: reloaded