- name: Update all packages and install nano on all hosts
  hosts: all
  remote_user: ec2-user
  become: yes
  gather_facts: false
  roles:
    - roles/common

- name: Install and start apache, create index.html on frontend servers
  hosts: frontend
  remote_user: ec2-user
  become: yes
  gather_facts: false
  roles:
    - roles/web